# Generated by Django 4.1.7 on 2023-03-10 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_product_category_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BR', 'Braclet'), ('NL', 'Neckpiece'), ('RG', 'Ring'), ('EG', 'Earrings'), ('EX', 'Exclusive'), ('CH', 'Charm'), ('PS', 'Peace'), ('AN', 'Anxiety'), ('DP', 'Depression'), ('HP', 'Happiness'), ('NG', 'Negativity'), ('AN', 'Amazonite'), ('', 'Aquamarine'), ('', 'Blue Gold Stone'), ('', 'Golden Quartz'), ('', 'Green Fluorite'), ('JP', 'Jasper'), ('', 'Garnet'), ('ML', 'Malachite'), ('OP', 'Opalite'), ('RQ', 'Rose Quartz'), ('', 'Selenite'), ('', 'Green Jade'), ('RH', 'Rhodonite'), ('', 'Pyrite'), ('', 'Strawberry Quartz'), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
