# Generated by Django 4.1.7 on 2023-04-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='context',
            field=models.TextField(default=' '),
        ),
    ]
