# Generated by Django 4.1.7 on 2023-04-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_category_product_category1_product_category2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category1',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category2',
        ),
    ]
