# Generated by Django 4.1.7 on 2023-04-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_category1_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='context',
        ),
    ]
