# Generated by Django 4.1.7 on 2023-04-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_product_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='composition',
            new_name='benefits',
        ),
    ]
