# Generated by Django 4.1.7 on 2023-04-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_composition_product_benefits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodapp',
            new_name='customization',
        ),
    ]
